### ISSUE TITLE
NDK Library Issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [appotry/ipcamera-for-android#46]
```
Hello Sir,

i m developing android since one year but i m new for android ndk builder so 
please can anyone guide me that how can i configure jni directory for this 
projects.i m using eclipse helios in windows. 

any help would be nice.

thanks.
```

Original issue reported on code.google.com by `hemenkan...@gmail.com` on 29 Oct 2012 at 6:28

**Comment by GoogleCodeExporter** [comment]
```
What phone are you using? It doesn't look like anyone is supporting this 
project any more. There a lot of things missing from this project for you to 
run  in once you  download it.
```

Original comment by `rickplea...@gmail.com` on 30 Oct 2012 at 2:08

**Comment by GoogleCodeExporter** [comment]
```
im using mac osx now and it seems that .so libraries can't run correctly in 
osx???

(I tested with real device but it's not working either. No error in LoadLibrary 
process but the native methods "nativeStartStreamingMedia" threw 
java.lang.UnsatisfiedLinkError.

So I am curious what these .so libraries do? Are they support as a http 
container? (If so I can try to replace it by other containers like Jetty.)

Thanks!!

11-07 13:15:41.556: ERROR/AndroidRuntime(8112): FATAL EXCEPTION: Thread-1697
        java.lang.UnsatisfiedLinkError: nativeStartStreamingMedia
        at com.example.NativeAgent.nativeStartStreamingMedia(Native Method)
        at com.example.NativeAgent.NativeStartStreamingMedia(NativeAgent.java:27)
        at com.example.MyActivity.startStreaming(MyActivity.java:202)
        at com.example.MyActivity.access$200(MyActivity.java:17)
        at com.example.MyActivity$4.onRequest(MyActivity.java:300)
        at com.example.StreamingServer.serve(StreamingServer.java:42)
        at com.example.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:430)
        at java.lang.Thread.run(Thread.java:856)
```

Original comment by `xdfh...@gmail.com` on 7 Nov 2012 at 6:41
